### PR TITLE
Added components and dependencies.

### PR DESCRIPTION
**Pull request by ybarr042**

### CODE REVIEW

**Review by cbroque95 — APPROVED** [review]
this file has been review by myself and Richard.

**Review by reaxster — APPROVED** [review]
This has been reviewed my myself and looks good, all test passed

**Review by reaxster — APPROVED** [review]
This has been reviewed my myself

**Review by reaxster — APPROVED** [review]

**Review by reaxster — APPROVED** [review]

**Review by cbroque95 — APPROVED** [review]
this has been reviewed by myself

**Review by fhernan22 — APPROVED** [review]

**Pull request merged**
